DemoWebApplication/Pages/Demo1.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Dynamics.DataEntities;
using Microsoft.OData.Client;
using Utilities;
using Newtonsoft.Json;
using System.IO;
using System.Net;
using System.Net.Http;
using Microsoft.IdentityModel.Clients.ActiveDirectory;

namespace DemoWebApplication.Pages
{
    public class Demo1Model : PageModel
    {
        private DataServiceResponse responce;
        [BindProperty]
        public string FailMessage { get; set; }
        [BindProperty]
        public string BathStatusCode { get;  set; }
        [BindProperty]
        public string Op1Status { get; set; }
        [BindProperty]
        public string Op2Status { get; set; }        
        public string Message { get; set; }
        [BindProperty]
        public SalesOrderHeader SalesOrderHeader { get; set; }      
        public SalesOrderLine SalesOrderLine { get; set; } = new SalesOrderLine();
        [BindProperty]
        public decimal ImputOrderQuantity { get; set; } = 1;
        [BindProperty]
        public string ImputOrderNumber { get; set; }
        [BindProperty]
        public string DeepLink { get; set; } = "";
        [BindProperty]
        public bool IsFail { get; set; }
        [BindProperty]
        public bool? IsPosted { get; set; } = null;
        public static List<Vendor> Customers { get; private set; } = new List<Vendor>();
        public List<SelectListItem> CustomerSelectItems { get; private set; }
        [BindProperty]
        public string SelectedCustomerAccount { get; set; }
        public Vendor SelectedCustomer { get; private set; }
        public List<DistinctProduct> Products { get; private set; }
        public List<SelectListItem> DistinctProducts { get; private set; }
        public string SelectedProductNumber{ get; set; }       
        public string IputProductNumber { get; set; }
        public DistinctProduct SelectedProduct { get; private set; }
        public string ProductNumber2Submit { get; private set; }

        public void OnGet() { }

        private static Resources Authenticate()
        {
            string ODataEntityPath = ConnectionSettings.Default.UriString + "data";
            Uri oDataUri = new Uri(ODataEntityPath, UriKind.Absolute);
            var context = new Resources(oDataUri);

            context.SendingRequest2 += new EventHandler<SendingRequest2EventArgs>(delegate (object sender, SendingRequest2EventArgs e)
            {
                var authenticationHeader = OAuthHandler.GetAuthenticationHeader(useWebAppAuthentication: true);
                e.RequestMessage.SetHeader(OAuthHandler.OAuthHeader, authenticationHeader);
            });
            return context;
        }

        //Demo 1.1
        public async Task<IEnumerable<SelectListItem>> GeCustomerAccountsAsync()
        {         
            Resources context = Authenticate();

            var customersList = await context.Vendors.ExecuteAsync();

            Customers = customersList.ToList();

            CustomerSelectItems = new List<SelectListItem>(Customers.Select(r => new SelectListItem
            {
                Value = r.VendorAccountNumber.ToString(),
                Text = r.VendorName + " - " + r.VendorAccountNumber,
            }));

            return CustomerSelectItems;
        }


        //Demo 1.2
        public async Task<IActionResult> OnPostSalesOrderLineAsync(string selectedCustomerAccount, string selectedProductNumber, string iputProductNumber)
        {
            Resources context = Authenticate();

            try
            {
                InitPurshaseOrderValues(selectedCustomerAccount, iputProductNumber, context);

                // 1. Single Changeset
                responce = await context.SaveChangesAsync(SaveChangesOptions.PostOnlySetProperties | SaveChangesOptions.BatchWithSingleChangeset);

                // 2. Independent Operations
                //responce = await context.SaveChangesAsync(SaveChangesOptions.PostOnlySetProperties | SaveChangesOptions.BatchWithIndependentOperations);

                BathStatusCode = responce.BatchStatusCode.ToString();
                Op1Status = responce.ElementAt(0).StatusCode.ToString();
                Op2Status = responce.ElementAt(1).StatusCode.ToString();
                DeepLink = GetDeepLinkString();

                IsPosted = true;
            }


            catch (DataServiceRequestException e)
            {
                IsPosted = false;

                var batchStatusCode = e.Response.BatchStatusCode;

                dynamic results = JsonConvert.DeserializeObject<dynamic>(e.InnerException.Message);
                var error = results.error.message;
                var errorDetails = results.error.innererror.message;
                FailMessage = error + " " + errorDetails;

                BathStatusCode = batchStatusCode.ToString();
                Op1Status = e.Response.ElementAt(0).StatusCode.ToString();
                Op2Status = Op1Status;
            }

            return null;
        }


        public async Task<IEnumerable<SelectListItem>> GetDistinctProductsAsync()
        {
            Resources context = Authenticate();

            var products = await context.DistinctProducts.ExecuteAsync();

            Products = products.ToList();

            DistinctProducts = new List<SelectListItem>(Products.Select(r => new SelectListItem
            {
                Value = r.ProductNumber.ToString(),
                Text = r.ProductName

            }));

            return DistinctProducts;
        }

        public void OnPostSalesOrderBody(string selectedCustomerAccount, string selectedProductNumber)
        {
            IputProductNumber = selectedProductNumber;
        }



        private string GetDeepLinkString()
        {
            Resources context = Authenticate();
            string sessionUrl = "/api/services/DeepLinkServices/DeepLinkSevice/getDeepLink";
            string GetUserSessionOperationPath = string.Format("{0}{1}", ConnectionSettings.Default.UriString.TrimEnd('/'), sessionUrl);

            var request = WebRequest.Create(GetUserSessionOperationPath);
            request.Headers[OAuthHandler.OAuthHeader] = OAuthHandler.GetAuthenticationHeader();
            request.Method = "POST";

            var requestContract = new
            {
                company = "usmf",
                menuItem = "PurchTableListPage",
                dataSource = "PurchTable",
                field = "PurchId",
                value = ImputOrderNumber
            };

            var requestContractString = JsonConvert.SerializeObject(requestContract);

            using (var stream = request.GetRequestStream())
            {
                using (var writer = new StreamWriter(stream))
                {
                    writer.Write(requestContractString);
                }
            }

            using (var response = (HttpWebResponse)request.GetResponse())
            {
                using (Stream responseStream = response.GetResponseStream())
                {
                    using (StreamReader streamReader = new StreamReader(responseStream))
                    {
                        return streamReader.ReadToEnd().ToString();                       

                    }
                }
            }  
        }

        private void InitPurshaseOrderValues(string selectedCustomerAccount, string iputProductNumber, Resources context)
        {
            //Purchase Order Header
            PurchaseOrderHeader purchaseOrder = new PurchaseOrderHeader();
            DataServiceCollection<PurchaseOrderHeader> purchaseOrderCollection = new DataServiceCollection<PurchaseOrderHeader>(context);
            purchaseOrderCollection.Add(purchaseOrder);

            purchaseOrder.CurrencyCode = "USD";
            purchaseOrder.PurchaseOrderNumber = ImputOrderNumber;
            purchaseOrder.InvoiceVendorAccountNumber = selectedCustomerAccount;
            purchaseOrder.OrderVendorAccountNumber = selectedCustomerAccount;
            purchaseOrder.LanguageId = "en-us";
            purchaseOrder.dataAreaId = "USMF";

            //Purchase Order Line
            PurchaseOrderLine purchaseOrderLine = new PurchaseOrderLine();
            DataServiceCollection<PurchaseOrderLine> purchaseOrderLineCollection = new DataServiceCollection<PurchaseOrderLine>(context);

            purchaseOrderLineCollection.Add(purchaseOrderLine);
            purchaseOrderLine.PurchaseOrderNumber = ImputOrderNumber;
            purchaseOrderLine.ItemNumber = iputProductNumber;
            purchaseOrderLine.OrderedPurchaseQuantity = ImputOrderQuantity;
            purchaseOrderLine.dataAreaId = "USMF";
        }
    }

    public class DeepLickContract
    {
        public string Company { get; set; }
        public string MenuItem { get; set; }
        public string DataSource { get; set; }
        public string Field { get; set; }
        public string Value { get; set; }
    }
}

DemoWebApplication/Pages/Demo2.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Dynamics.DataEntities;
using Microsoft.OData.Client;
using Utilities;
using Microsoft.IdentityModel.Clients.ActiveDirectory;
using System.Net.Http;
using Newtonsoft.Json.Linq;

namespace DemoWebApplication.Pages
{
    public class Demo2Model : PageModel
    {
        public string Message { get; set; }

        public string ProductID { get; set; }

        public List<SelectListItem> DistinctProducts { get; set; }
        public string OnhandData { get; private set; }
        public string NotAvailableMessage { get; private set; }

        public void OnGet() { }

        private static Resources Authenticate()
        {
            string ODataEntityPath = ConnectionSettings.Default.UriString + "data";
            Uri oDataUri = new Uri(ODataEntityPath, UriKind.Absolute);
            var context = new Resources(oDataUri);

            context.SendingRequest2 += new EventHandler<SendingRequest2EventArgs>(delegate (object sender, SendingRequest2EventArgs e)
            {
                var authenticationHeader = OAuthHandler.GetAuthenticationHeader(useWebAppAuthentication: true);
                e.RequestMessage.SetHeader(OAuthHandler.OAuthHeader, authenticationHeader);
            });
            return context;
        }

        public async Task<IEnumerable<SelectListItem>> GetDistinctProductsAsync()
        {
             Resources context = Authenticate();           

            var distinctProducts = await context.DistinctProducts.ExecuteAsync();

            
            DistinctProducts = new List<SelectListItem>(distinctProducts.Select(r => new SelectListItem
            {
                Value = r.ProductNumber.ToString(),
                Text = r.ProductName

            }));

            return DistinctProducts;
        }        

        public async Task<IActionResult> OnPostAsyncOdata(string productID)
        {
            Resources context = Authenticate();

            var productsOnhad = await context.InventorySitesOnHand.ExecuteAsync();

            var productOnhad = productsOnhad.Where(x => x.ItemNumber == productID).FirstOrDefault();

            GetOnhadArray(productOnhad);

            return null;
        }
        //Demo 2.1
        public async Task<IActionResult> OnPostAsync(string productID)
        {
            try
            {
                string clientId = ConnectionSettings.Default.ApimClientId;
                string ClientSecreet = ConnectionSettings.Default.ApinClientSecreet;
                string tenant = ConnectionSettings.Default.ApinOauthTenant;
                string resource = ConnectionSettings.Default.ActiveDirectoryResource;
                string subscriptionKey = ConnectionSettings.Default.ApinSubscriptionKey;

                //1. Authenticate via custom OAuth 2.0 service
                AuthenticationContext authenticationContext = new AuthenticationContext(tenant, false);

                var creadential = new ClientCredential(clientId, ClientSecreet);
                AuthenticationResult authenticationResult = authenticationContext.AcquireTokenAsync(resource, creadential).Result;

                        
                var authorizationToken = authenticationResult.AccessTokenType + " "  + authenticationResult.AccessToken;

                //2. Call Azure API        
                var client = new HttpClient();

                // Create headers
                client.DefaultRequestHeaders.Add("Ocp-Apim-Subscription-Key", subscriptionKey);
                client.DefaultRequestHeaders.Add("Authorization", authorizationToken);

                string uri = "https://dyn365.azure-api.net/Warehouses/OnHand/" + productID;

                //Request call
                var request = await client.GetAsync(uri);
                string responseBody = await request.Content.ReadAsStringAsync();

                SetOnHandArray(responseBody);
            }
            catch ( Exception e)
            {
                throw new Exception(e.Message);
            }
            return null;
        }

        private void SetOnHandArray(string responseBody)
        {
            var o = JObject.Parse(responseBody);

            var values = o["value"];

            if (values.Count() == 0)
            {
                OnhandData = null;
                NotAvailableMessage = "Unavailable ☹";
            }
            else
            {
                values = values.First();

                if (values != null && ((decimal)values["OnHandQuantity"] + (decimal)values["ReservedOnHandQuantity"] + (decimal)values["OrderedQuantity"]) > 0)
                {
                    OnhandData = "[ " + (decimal)values["OnHandQuantity"] + " , " + (decimal)values["ReservedOnHandQuantity"] + " , " + (decimal)values["OrderedQuantity"] + " ]";
                    NotAvailableMessage = null;
                }
                else
                {
                    OnhandData = null;
                    NotAvailableMessage = "Unavailable ☹";
                }
            }
        }

        private void GetOnhadArray(InventorySiteOnHand productOnhad)
        {
            if (productOnhad != null && (productOnhad.OnHandQuantity + productOnhad.ReservedOnHandQuantity + productOnhad.OrderedQuantity) > 0)
            {
                OnhandData = "[ " + productOnhad.OnHandQuantity + " , " + productOnhad.ReservedOnHandQuantity + " , " + productOnhad.OrderedQuantity + " ]";
                NotAvailableMessage = null;
            }
            else
            {
                OnhandData = null;
                NotAvailableMessage = "Unavailable ☹";
            }
        }
    }
}

DemoWebApplication/Pages/Demo3.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DemoWebApplication.Pages
{
    public class Demo3tModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "This demo tree";
        }
    }
}

DemoWebApplication/Pages/Demo4.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DemoWebApplication.Pages
{
    public class Demo4Model : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "This is demo four";
        }
    }
}

DemoWebApplication/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DemoWebApplication.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

DemoWebApplication/Pages/Demo1.cshtml
@page
@using Microsoft.Dynamics.DataEntities;
@using Microsoft.OData.Client;
@model Demo1Model
@{
    ViewData["Title"] = "Demo 1 - Synchronous integration - OData";
}
<h4>@ViewData["Title"]</h4>
@*<h3>@Model.Message</h3>*@

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>



<div>

    <div class="row" style="margin-left:5px">
        <img style="margin-left:4px" width="50" src="~/images/Azure App Service_COLOR.png" />
        <img style="margin-left:4px" width="50" src="~/images/Azure Active Directory_COLOR.png" />
        <img style="margin-left:4px" width="50" src="~/images/odata.png" />
        <img style="margin-left:4px" width="50" src="~/images/FO.png" />
    </div>
    <hr />
    <div>

        <h3>Purchase order header</h3>
        
        <form method="post" asp-page-handler="SalesOrderBody">
            <div>

                <div class="row">

                    <div class="col-md-2">
                        <label>Vendor account</label>
                        @Html.DropDownListFor(model => model.SelectedCustomerAccount, Model.GeCustomerAccountsAsync().Result, "Select...", new { @class = "form-control", onchange = "this.form.submit();" })
                    </div>
                    <div class="col-sm-3">
                        <label>Order number</label>
                        <input asp-for="ImputOrderNumber" class="form-control" />
                    </div>
                </div>

            </div>
            <hr />
            <h3>Order lines</h3>
            <br />
            <div class="row">
                <div class="col-sm-4">
                    <label>Product name</label>
                    @Html.DropDownListFor(model => model.SelectedProductNumber, Model.GetDistinctProductsAsync().Result, "Select...", new { @class = "form-control", onchange = "this.form.submit();" })
                </div>
                <div class="col-sm-2">
                    <label>Quantity</label>
                    <input asp-for="ImputOrderQuantity" class="form-control">
                </div>
            </div>
            <br />
            <div class="row">

                <div class="col-sm-3">
                    <label>Product number (w/o validation)</label>
                    <input asp-for="IputProductNumber" class="form-control" />
                </div>
            </div>
            <hr />
            <input type="submit" asp-page-handler="SalesOrderLine" value="Submit" class="btn btn-primary" />
            <a class="btn btn-default" href="./Demo1">Cancel</a>
            <hr />
            <div class="center-block">
                @if (Model.IsPosted != null)
                {
                    <div lass="center-block">
                        @if (Model.IsPosted == false)
                        {
                            <div class="row">
                                <div class="col-sm-1">
                                    <img src="~/images/fail.png" />
                                </div>
                                <div class="col-sm-1">
                                    <h6>Batch</h6>
                                    @if (Model.BathStatusCode == "200")
                                    {
                                        <h6 style="color:limegreen">@Model.BathStatusCode</h6>
                                    }
                                    else
                                    {
                                        <h6 style="color:crimson">@Model.BathStatusCode</h6>
                                    }

                                </div>
                                <div class="col-sm-1">
                                    <h6>Operation 1</h6>
                                    @if (Model.Op1Status == "200" || Model.Op1Status == "201")
                                    {
                                        <h6 style="color:limegreen">@Model.Op1Status</h6>
                                    }
                                    else
                                    {
                                        <h6 style="color:crimson">@Model.Op1Status</h6>

                                    }
                                </div>
                                <div class="col-sm-1">

                                    <h6>Operation 2</h6>
                                    @if (Model.Op2Status == "200" || Model.Op2Status == "201")
                                    {

                                        <h6 style="color:limegreen">@Model.Op2Status</h6>
                                    }
                                    else
                                    {

                                        <h6 style="color:crimson">@Model.Op2Status</h6>
                                    }
                                </div>
                            </div>
                            <br />
                            <h6 style="color:crimson">@Model.FailMessage</h6>
                        }
                        else
                        {
                            <div class="row">
                                <div class="col-sm-1">
                                    <img src="~/images/check.png" />
                                </div>
                                <div class="col-sm-1">
                                    <h6>Batch</h6>
                                    <h6 style="color:limegreen">@Model.BathStatusCode</h6>
                                </div>
                                <div class="col-sm-1">
                                    <h6>Operation 1</h6>
                                    @if (Model.Op1Status == "200" || Model.Op1Status == "201")
                                    {
                                        <h6 style="color:limegreen">@Model.Op1Status</h6>
                                    }
                                    else
                                    {
                                        <h6 style="color:crimson">@Model.Op1Status</h6>

                                    }
                                </div>
                                <div class="col-sm-1">
                                    <h6>Operation 2</h6>
                                    @if (Model.Op2Status == "200" || Model.Op2Status == "201")
                                    {
                                        <h6 style="color:limegreen">@Model.Op2Status</h6>
                                    }
                                    else
                                    {
                                        <h6 style="color:crimson">@Model.Op2Status</h6>
                                    }
                                </div>
                            </div>
                            <br />
                            var url = "<a href=" + Model.DeepLink + ">Go to order</a>";
                            //string textrev = url;
                            @Html.Raw(url)
                            <div>
                                <textbox style="font-size:x-small;">[Secured URL]</textbox>
                            </div>
                        }
                    </div>
                }
            </div>
        </form>

    </div>


</div>

DemoWebApplication/Pages/Demo2.cshtml
@page
@model Demo2Model
@{
    ViewData["Title"] = "Demo 2 - Synchronous integration – Azure API Management";
}
<h4>@ViewData["Title"]</h4>

<div class="row" style="margin-left:5px">
    <img width="50" src="~/images/Azure App Service_COLOR.png" />
    <img style="margin-left:4px" width="50" src="~/images/Azure Active Directory_COLOR.png" />
    <img style="margin-left:4px" width="50" src="~/images/Azure Security Center _COLOR.png" />
    <img style="margin-left:4px" width="50" src="~/images/Azure API Management_COLOR.png" />
    <img style="margin-left:4px" width="50" src="~/images/odata.png" />
    <img style="margin-left:4px" width="50" src="~/images/FO.png" />
</div>
<hr />

<div>
    @*<h1> @{ViewData["Title"] = "Demo 2 - Synchronous integration – Azure API Management";}</h1>*@
    <div class="row">
        <div class="col-sm-4">
            @using (Html.BeginForm("Demo2", "Demo2Model", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                @Html.DropDownListFor(model => model.ProductID, Model.GetDistinctProductsAsync().Result, "Select a product...", new { @class = "form-control", onchange = "this.form.submit();" })
            }
        </div>
        <div class="col-sm-8"></div>
    </div>
    <br />
    <p1>@Model.NotAvailableMessage</p1>
    <div class="row">
        <div class="col-sm-3">
            <canvas id="myChart" width="50" height="50"></canvas>
        </div>
        <div class="col-sm-8"></div>
    </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.js"></script>
<script>
            var ctx = document.getElementById("myChart").getContext('2d');
            var myChart = new Chart(ctx, {
                type: 'pie',
                data: {
                    labels: ["Available", "Reserved", "Ordered"],
                    datasets: [{
                        label: 'OnHand',
                        data: @Model.OnhandData,
                        backgroundColor: [
                            'rgba(0, 114, 198, 1)',
                            'rgba(154, 154, 154, 1)',
                            'rgba(54, 162, 235, 1)',

                            'rgba(75, 192, 192, 0.2)',
                            'rgba(153, 102, 255, 0.2)',
                            'rgba(255, 159, 64, 0.2)'
                        ],
                        borderColor: [
                            'rgba(255,99,132,1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(255, 206, 86, 1)',
                            'rgba(75, 192, 192, 1)',
                            'rgba(153, 102, 255, 1)',
                            'rgba(255, 159, 64, 1)'
                        ],
                        borderWidth: 0
                    }]
                },
                options: {

                    plugins: {
                        datalabels: {
                            display: function (context) {
                                return context.dataset.data[context.dataIndex] >= 0.0
                            }
                        }
                    },


                    events: false,
                    animation: {
                        duration: 500,
                        easing: "easeOutQuart",
                        onComplete: function () {
                            var ctx = this.chart.ctx;
                            ctx.font = Chart.helpers.fontString(Chart.defaults.global.defaultFontFamily, 'normal', Chart.defaults.global.defaultFontFamily);
                            ctx.textAlign = 'center';
                            ctx.textBaseline = 'bottom';

                            this.data.datasets.forEach(function (dataset) {

                                for (var i = 0; i < dataset.data.length; i++) {
                                    var model = dataset._meta[Object.keys(dataset._meta)[0]].data[i]._model,
                                        total = dataset._meta[Object.keys(dataset._meta)[0]].total,
                                        mid_radius = model.innerRadius + (model.outerRadius - model.innerRadius) / 2,
                                        start_angle = model.startAngle,
                                        end_angle = model.endAngle,
                                        mid_angle = start_angle + (end_angle - start_angle) / 2;

                                    var x = mid_radius * Math.cos(mid_angle);
                                    var y = mid_radius * Math.sin(mid_angle);

                                    ctx.fillStyle = '#fff';
                                    if (i == 3) { // Darker text color for lighter background
                                        ctx.fillStyle = '#444';
                                    }
                                    var percent = String(Math.round(dataset.data[i] / total * 100)) + "%";
                                    ctx.fillText(dataset.data[i], model.x + x, model.y + y);
                                    // Display percent in another line, line break doesn't work for fillText
                                    //ctx.fillText(percent, model.x + x, model.y + y + 15);
                                }
                            });
                        }
                    },


                }
    });

</script>

DemoWebApplication/Pages/Demo3.cshtml
@page
@model Demo3tModel
@{
    ViewData["Title"] = "Demo 3";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

DemoWebApplication/Pages/Demo4.cshtml
@page
@model Demo4Model
@{
    ViewData["Title"] = "Demo 4";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

DemoWebApplication/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Dynamics 365 F&O Integration Demo";
}
<h2>@ViewData["Title"]</h2>

@*<div class="container-fluid">
    <h1> @{ViewData["Title"] = "Dynamics 365 F&O integration demo";}</h1>
    <div class="row">
        <div class="col-sm-4">
            @using (Html.BeginForm("Index", "IndexModel", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                @Html.DropDownListFor(model => model.ProductID, Model.GetDistinctProductsAsync().Result, "Select a product...", new { @class = "form-control", onchange = "this.form.submit();" })
            }
        </div>
        <div class="col-sm-8"></div>
    </div>
    <br />
    <p1>@Model.NotAvailableMessage</p1>
    <div class="row">
        <div class="col-sm-3">
            <canvas id="myChart" width="50" height="50"></canvas>
        </div>
        <div class="col-sm-8"></div>
    </div>
</div>*@